Repository shivin9/BT3103, pull requests merged in 2020-09, with the labels that each got.

#67 A0189054X
  A0189045X.txt
  README.md
  runlin.txt
Labels: Please Fix README, enhancement

#32 added email txt file
  shuhang.txt
Labels: Merge Conflict exercise not done

#14 BT3103: NUS Discovery path exercise (Github)
  A0182695N.txt
  mitchellkwong.txt
Labels: Please Fix README

#35 Added self-introduction (Nelly)
  A0185881N.txt
  nelly.txt
Labels: Please Fix README

#38 Added intro
  A0196695E.txt
Labels: Merge Conflict exercise not done

#59 adding junhan's file
  A0202989R.txt
  junhan.txt
Labels: enhancement

#70 Merge conflict exercise
  .DS_Store
  .gitignore
  A0200127B.txt
  README.md
  dillon.txt
Labels: Merge Conflict exercise not done

#49 PR from Shichao
  A0188499Y.txt
  shichao.txt
Labels: Please Fix README
